version: '3'

services:
  postgres-compose-env1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /F/Git/semanaDev:/var/lib/postgresql/data
    working_dir: "/var/lib/postgresql/data"
    networks:
      - postgres-compose-network

  pg-admin-compose-env1:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "matheus.cn10@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose-env1
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge